# Change these first
owner: opott
repo: status

sites:
  - name: Portfolio
    url: https://opott.uk
  - name: Status Page
    url: https://status.opott.uk
  - name: CourseNotes
    url: https://notes.opott.uk

status-website:
  cname: status.opott.uk
  logoUrl: https://avatars.githubusercontent.com/u/120502505?v=4
  name: Oliver Potter
  introTitle: "Check the status of all of **Oliver Potter**'s services."
  introMessage:
  navbar:
    - title: Home
      href: https://opott.uk

assignees:
  - opott

i18n:
  footer: 
